<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-21T09:29:47 IST" name="Suite" finished-at="2022-09-21T09:30:05 IST" duration-ms="18928">
    <groups>
    </groups>
    <test started-at="2022-09-21T09:29:47 IST" name="Error Validation Test" finished-at="2022-09-21T09:29:54 IST" duration-ms="7543">
      <class name="com.rahulshettyacademy.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.rahulshettyacademy.tests.ErrorValidationsTest@4dbb42b7]" started-at="2022-09-21T09:29:47 IST" name="launchApplication" finished-at="2022-09-21T09:29:51 IST" duration-ms="4301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="endToEnd()[pri:0, instance:com.rahulshettyacademy.tests.ErrorValidationsTest@4dbb42b7]" started-at="2022-09-21T09:29:51 IST" name="endToEnd" finished-at="2022-09-21T09:29:51 IST" duration-ms="372" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or ,password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or ,password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.rahulshettyacademy.tests.ErrorValidationsTest.endToEnd(ErrorValidationsTest.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endToEnd -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.rahulshettyacademy.tests.ErrorValidationsTest@4dbb42b7]" started-at="2022-09-21T09:29:51 IST" name="tearDown" finished-at="2022-09-21T09:29:51 IST" duration-ms="127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.rahulshettyacademy.tests.ErrorValidationsTest@4dbb42b7]" started-at="2022-09-21T09:29:51 IST" name="launchApplication" finished-at="2022-09-21T09:29:53 IST" duration-ms="1877" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="endToEnd()[pri:0, instance:com.rahulshettyacademy.tests.ErrorValidationsTest@4dbb42b7]" started-at="2022-09-21T09:29:53 IST" name="endToEnd" finished-at="2022-09-21T09:29:54 IST" duration-ms="336" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or ,password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or ,password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.rahulshettyacademy.tests.ErrorValidationsTest.endToEnd(ErrorValidationsTest.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endToEnd -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.rahulshettyacademy.tests.ErrorValidationsTest@4dbb42b7]" started-at="2022-09-21T09:29:54 IST" name="tearDown" finished-at="2022-09-21T09:29:54 IST" duration-ms="93" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.rahulshettyacademy.tests.ErrorValidationsTest -->
    </test> <!-- Error Validation Test -->
    <test started-at="2022-09-21T09:29:47 IST" name="Stand Alone Test" finished-at="2022-09-21T09:30:05 IST" duration-ms="18928">
      <class name="com.rahulshettyacademy.tests.StandAloneTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:29:47 IST" name="launchApplication" finished-at="2022-09-21T09:29:52 IST" duration-ms="5282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:29:52 IST" name="submitOrder" data-provider="getData" finished-at="2022-09-21T09:29:56 IST" duration-ms="3794" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Myacademy@007, email=cjasraj98@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:29:56 IST" name="tearDown" finished-at="2022-09-21T09:29:56 IST" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:29:56 IST" name="launchApplication" finished-at="2022-09-21T09:29:59 IST" duration-ms="3060" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:29:59 IST" name="submitOrder" data-provider="getData" finished-at="2022-09-21T09:30:03 IST" duration-ms="3691" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Myacademy@007, email=cjasraj98@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:30:03 IST" name="tearDown" finished-at="2022-09-21T09:30:03 IST" duration-ms="95" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:30:03 IST" name="launchApplication" finished-at="2022-09-21T09:30:05 IST" duration-ms="1843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistoryTest()[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:30:05 IST" name="orderHistoryTest" finished-at="2022-09-21T09:30:05 IST" depends-on-methods="com.rahulshettyacademy.tests.StandAloneTest.submitOrder" duration-ms="709" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.rahulshettyacademy.tests.StandAloneTest@f0c8a99]" started-at="2022-09-21T09:30:05 IST" name="tearDown" finished-at="2022-09-21T09:30:05 IST" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.rahulshettyacademy.tests.StandAloneTest -->
    </test> <!-- Stand Alone Test -->
  </suite> <!-- Suite -->
</testng-results>
